version: "3"
services:
  server:
    container_name: server-prod
    restart: always
    expose: 
      - "5000"
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "5000:5000"
    links:
      - mongo
    environment:
      - PORT=5000
      - NODE_ENV="production"
      - JWT_SECRET="thisismysupersecrettokenjustkidding"
      - DATABASE_URL="mongodb://mongo:27017/donut-development"
      - SENDGRID_API_KEY='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'
      - SOCKET_PORT=8810
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
volumes:
  db-data:
