version: "3"
services:
  server:
    container_name: server
    restart: always
    expose:
      - "5000"
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/server
    ports:
      - "5000:5000"
    links:
      - mongo
    env_file:
      - .env.dev
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - db-data:/data/db
    ports:
      - "27017:27017"
  redis:
    container_name: redis
    image: redis:5-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass auth
volumes:
  db-data:
  redis-data:
